### ISSUE TITLE
Connect this driver to the "Behat\MinkExtension" project

### ISSUE THREAD

**Issue by aik099** [minkphp/webdriver-classic-driver#15]
Currently, there is no way to use this driver in the Behat, because there is no corresponding driver in the https://github.com/Behat/MinkExtension/tree/master/src/Behat/MinkExtension/ServiceContainer/Driver .

The driver key would be `webdriver-classic` instead of `selenium2`. The current Selenium2 driver could be used as a starting point.

@uuf6429 , please submit a PR to that repo.

**Comment by uuf6429** [comment]
@aik099 / @stof just one question, out of curiosity, why are the driver factories in the `behat/mink-extension` package, instead of each individual driver package?

**Comment by aik099** [comment]
I've just noticed a huge banner on top of https://github.com/Behat/MinkExtension that recommends using https://github.com/FriendsOfBehat/MinkExtension instead.

@stof , isn't there a way to have a single repo?

**Comment by uuf6429** [comment]
@stof

> there is a single repo for the MinkExtension now: the FriendsOfBehat one

`FriendsOfBehat/MinkExtension` is a bit of a mess:
1. it lacks proper documentation/readme, referring to the old/to-be-archived one instead (even though it has its own `doc` dir)
2. it claims not take any updates/features/improvements, unless they are compatibility bugfixes
3. looking at the code, it could do with some updating, but the previous point makes that unlikely to happen

I'll open a PR nonetheless, but this situation, (on top of the lack of feedback in Behat PRs/issues), doesn't inspire much confidence in Behat/Mink TBH.

@aik099 I'm closing this issue since it doesn't have anything to do with `webdriver-classic-driver` anymore.
