### ISSUE TITLE
Move test web server startup/shutdown to the GitHub Actions workflow

### ISSUE THREAD

**Issue by aik099** [minkphp/webdriver-classic-driver#22]
Currently, the https://github.com/minkphp/webdriver-classic-driver/blob/main/tests/bootstrap.php file automatically starts/stops the web server with test fixtures used during testing. This is an innovative approach compared to how other drivers would do this.

If we go away from the current approach (start web server inside a test suite), then all that stuff needs to be moved into the GitHub Actions workflow (as in other drivers).

### Possible downsides to the current approach (I'm not saying it's a wrong approach in general):

* Project contributors might already have a Web Server running locally and this project cloned in its DocumentRoot. In that scenario, they don't need another Web Server to be started and only need to map paths in the `phpunit.xml`.
* The 8002 port might be already occupied on the contributor's machine, which would result in the inability to run tests.
* The Symfony's Process component is being used, but it's not explicitly listed as a dev dependency in the composer and that means, that it's not guaranteed to be present as a dependency.

**Comment by uuf6429** [comment]
Another downside:
- developers cannot try pages in the test server without either running the server manually, or run tests with a debugger+breakpoint, very long sleep or similar.

On the positive side:
- developers do not need to remember to start the web server
- we can avoid having this step all over the place (contrib md, github actions)
- in case of port conflicts, we _could_ make it somehow allocate and use an unused arbitrary port

> The Symfony's Process component is being used, but it's not explicitly listed as a dev dependency in the composer and that means, that it's not guaranteed to be present as a dependency.

That's a good point, I'll fix that.

**Comment by aik099** [comment]
> in case of port conflicts, we could make it somehow allocate and use an unused arbitrary port

The default port can be specified through the environment variable (as we do with other test-related stuff) in the `phpunit.xml.dist` file.

**Comment by uuf6429** [comment]
> - Project contributors might already have a Web Server running locally and this project cloned in its DocumentRoot.

Interestingly, the original process bound to that port would receive the requests. For some reason PHP doesn't complain that the port is already in use.

Worst case is that the original server's purpose was unrelated to these tests, so the tests start failing, confusing the user.

But that case would happen anyway with the old manual flow.

> - The 8002 port might be already occupied on the contributor's machine, which would result in the inability to run tests.

They'll need to change that in the config then. That also applies to other ports (e.g. defined in docker).

> - The Symfony's Process component is being used, but it's not explicitly listed as a dev dependency in the composer and that means, that it's not guaranteed to be present as a dependency.

Fixed in #23.

> - The default port can be specified through the environment variable (as we do with other test-related stuff) in the `phpunit.xml.dist` file.

Will be fixed #34 and documentation improved in #19.

----

A small reminder of why this was done: we should strive for the simplest way possible for contributors to start out. This is why we use tools like package managers, containerisation and so on.

With all that, I feel that this issue can be closed.
