### ISSUE TITLE
Initial Release Roadmap

### ISSUE THREAD

**Issue by aik099** [minkphp/webdriver-classic-driver#31]
What needs to be done before a driver will have its first release?

My recent activity related to this driver:
* added support to the PHPUnit-Mink project ( https://github.com/minkphp/phpunit-mink/pull/138 )
* added an issue about documenting in Behat MinkExtension ( https://github.com/FriendsOfBehat/MinkExtension/issues/30 )

// cc: @uuf6429

**Comment by uuf6429** [comment]
Hi!

I would have made a "1.0" prerelease a long time ago, but wanted to avoid a lot of discussion on that and then somehow forgot about it.

We've been using this driver at work on a daily bases and so far it seems quite stable, with the exception of [this issue](https://github.com/minkphp/webdriver-classic-driver/issues/30) which I think we should solve (the fix is simple, but I was hoping to get some agreement first).

**Comment by aik099** [comment]
> I would have made a "1.0" prerelease a long time ago, but wanted to avoid a lot of discussion on that and then somehow forgot about it.

Please create a release so I can use this `^1.0` version constraint in `composer.json` instead of `@dev-main`.

> We've been using this driver at work on a daily bases and so far it seems quite stable, with the exception of [this issue](https://github.com/minkphp/webdriver-classic-driver/issues/30) which I think we should solve (the fix is simple, but I was hoping to get some agreement first).

I responded to the issue mentioned.

P.S.
Thanks to the code of this driver I was able to get MinkSelenium2Driver to work on Selenium 3 with the exception of right-clicking. This is as far as I could get considering https://github.com/instaclick/php-webdriver is in almost abandoned state (7 months without commits).

**Comment by uuf6429** [comment]
Done.
