### ISSUE TITLE
Squash PRs

### ISSUE THREAD

**Issue by uuf6429** [minkphp/webdriver-classic-driver#35]
@stof can you please set the default GitHub merge option to "squash"?

**Comment by aik099** [comment]
@uuf6429 , for me if I’ve squashed last PR, then on next PR I’ll get squash merge option selected by default. 

Checked in repo settings and haven’t found the setting you’ve requested.

**Comment by uuf6429** [comment]
![{397D8B20-7F4F-4FAC-AF55-F9F2ACF61578}](https://github.com/user-attachments/assets/f1f5ec52-47f2-43d3-b0b0-d95c4557ea22)

I guess we need to uncheck the other options then?

I realised this when I saw the relatively messy commit history for the `main` branch.

**Comment by aik099** [comment]
I've found https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github article explaining the usage of each of these merge strategies.

As you can see there is no way to change the default, but only to disable other merge strategies. IMO that is too much, because sometimes keeping commits of the original branch helps to understand what's going on.

Maybe you can ask GitHub Support to add such a feature?

**Comment by uuf6429** [comment]
> IMO that is too much, because sometimes keeping commits of the original branch helps to understand what's going on.

That should never happen - commit messages are internal to each PR, and in any case one can always refer back to the PR for what happened exactly (not sure about GitHub, but it might even be able to refer to the original commits in the PR).

In an case, there's more harm selecting the wrong merge method than there is from not being able to select merge instead of squash.

**Comment by aik099** [comment]
Done.
